# rift project configuration file

name = "storage"

[contracts.storage]
    contract = "Storage"
    deploy = "deploy_storage" # Will create later
    tests = [
        "test_storage" # Will create later
    ]
